# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMRxSwiftTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMRxSwiftTest

  target 'MVVMRxSwiftTestTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'RxTest'
    pod 'RxNimble/RxTest'
  end

  target 'MVVMRxSwiftTestUITests' do
    # Pods for testing
  end

  pod 'RxSwift'
  pod 'RxCocoa'

end
